ALTER TABLE "HeaderSettings"
  ADD COLUMN IF NOT EXISTS "logoVariant" TEXT NOT NULL DEFAULT 'wordmark',
  ADD COLUMN IF NOT EXISTS "logoImageUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "logoDarkImageUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "logoAlt" TEXT NOT NULL DEFAULT 'Carvi Associates',
  ADD COLUMN IF NOT EXISTS "logoHref" TEXT NOT NULL DEFAULT '/',
  ADD COLUMN IF NOT EXISTS "logoMarkText" TEXT NOT NULL DEFAULT 'C',
  ADD COLUMN IF NOT EXISTS "logoPrimaryText" TEXT NOT NULL DEFAULT 'Carvi',
  ADD COLUMN IF NOT EXISTS "logoSecondaryText" TEXT NOT NULL DEFAULT 'Associates',
  ADD COLUMN IF NOT EXISTS "showLogoMark" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "logoHeightDesktop" INTEGER NOT NULL DEFAULT 46,
  ADD COLUMN IF NOT EXISTS "logoHeightMobile" INTEGER NOT NULL DEFAULT 36;

ALTER TABLE "BlogSectionSettings"
  ADD COLUMN IF NOT EXISTS "archiveHeroOverlay" INTEGER NOT NULL DEFAULT 82,
  ADD COLUMN IF NOT EXISTS "archiveHeroHeight" TEXT NOT NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS "archiveHeroAlign" TEXT NOT NULL DEFAULT 'center',
  ADD COLUMN IF NOT EXISTS "archiveShowCrumbs" BOOLEAN NOT NULL DEFAULT true;
