import { SITE_DESCRIPTION, SITE_NAME, SITE_URL } from "@/lib/site-config";
import type {
  SeoFaqItem,
  SeoRobotsRuleItem,
  SeoSettingsContent,
} from "@/lib/seo/types";

export const defaultSeoSettings: SeoSettingsContent = {
  siteName: SITE_NAME,
  siteShortName: "Carvi",
  siteUrl: SITE_URL,
  defaultTitle: `${SITE_NAME} | Chartered Accountants for Audit, Tax & GST`,
  titleTemplate: `%s | ${SITE_NAME}`,
  applyTitleTemplate: true,
  defaultDescription: SITE_DESCRIPTION,
  defaultKeywords:
    "chartered accountants, audit firm, income tax filing, GST registration, ROC compliance, business advisory, bookkeeping, India",
  siteLanguage: "en",
  siteLocale: "en_IN",
  alternateLocales: [],
  applicationName: SITE_NAME,
  publisherName: SITE_NAME,
  authorName: SITE_NAME,
  generatorName: "",
  copyrightText: `© ${new Date().getFullYear()} ${SITE_NAME}`,
  categoryMeta: "Finance",
  referrerPolicy: "origin-when-cross-origin",
  colorScheme: "light",
  formatDetectionTelephone: false,
  faviconUrl: "/images/favicons/favicon-32x32.png",
  faviconSmallUrl: "/images/favicons/favicon-16x16.png",
  appleTouchIconUrl: "/images/favicons/apple-touch-icon.png",
  svgIconUrl: "",
  maskIconUrl: "",
  maskIconColor: "#5c6b45",
  themeColorLight: "#faf5e9",
  themeColorDark: "#211c13",
  indexingEnabled: true,
  defaultNoIndex: false,
  defaultNoFollow: false,
  defaultNoArchive: false,
  defaultNoSnippet: false,
  defaultNoImageIndex: false,
  maxSnippet: -1,
  maxImagePreview: "LARGE",
  maxVideoPreview: -1,
  robotsEnabled: true,
  robotsUseCustom: false,
  robotsCustomContent: "",
  robotsExtraLines: "",
  robotsHost: "",
  robotsCrawlDelay: null,
  blockAiCrawlers: false,
  allowedAiCrawlers: [],
  sitemapEnabled: true,
  sitemapIncludeImages: true,
  sitemapIncludeBlog: true,
  sitemapIncludeServices: true,
  sitemapIncludeCategories: true,
  sitemapIncludeTags: false,
  sitemapIncludeAuthors: true,
  sitemapIncludePages: true,
  sitemapDefaultChangeFreq: "WEEKLY",
  sitemapHomePriority: 1,
  sitemapPagePriority: 0.7,
  sitemapBlogPriority: 0.9,
  sitemapPostPriority: 0.8,
  sitemapServicePriority: 0.8,
  sitemapMaxUrls: 5000,
  ogType: "website",
  ogSiteName: SITE_NAME,
  ogImageUrl: "/images/blog/blog-1-1.jpg",
  ogImageAlt: `${SITE_NAME} — Chartered Accountants`,
  ogImageWidth: 1200,
  ogImageHeight: 630,
  twitterCard: "SUMMARY_LARGE_IMAGE",
  twitterSite: "",
  twitterCreator: "",
  twitterImageUrl: "",
  facebookAppId: "",
  facebookPageUrl: "",
  googleSiteVerification: "",
  bingSiteVerification: "",
  yandexVerification: "",
  yahooVerification: "",
  pinterestVerification: "",
  facebookDomainVerification: "",
  baiduVerification: "",
  nortonVerification: "",
  customVerifications: [],
  organizationEnabled: true,
  organizationType: "ACCOUNTING_SERVICE",
  organizationName: SITE_NAME,
  organizationLegalName: "Carvi & Associates",
  organizationAlternateName: "Carvi Associates Chartered Accountants",
  organizationDescription: SITE_DESCRIPTION,
  organizationLogoUrl: "/images/logo-dark.png",
  organizationImageUrl: "",
  foundingDate: "",
  founderName: "",
  contactEmail: "",
  contactPhone: "",
  faxNumber: "",
  priceRange: "$$",
  currenciesAccepted: "INR",
  paymentAccepted: "Cash, UPI, Bank Transfer, Credit Card",
  streetAddress: "",
  addressLocality: "",
  addressRegion: "",
  postalCode: "",
  addressCountry: "IN",
  latitude: "",
  longitude: "",
  hasMapUrl: "",
  areaServed: ["India"],
  openingHours: [
    { days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "10:00", closes: "19:00" },
    { days: ["Saturday"], opens: "10:00", closes: "15:00" },
  ],
  sameAs: [],
  contactPoints: [],
  knowsAbout: [
    "Statutory Audit",
    "Income Tax",
    "Goods and Services Tax",
    "Company Incorporation",
    "ROC Compliance",
    "Transfer Pricing",
    "Business Advisory",
  ],
  awards: [],
  slogan: "",
  numberOfEmployees: null,
  taxId: "",
  vatId: "",
  registrationNumber: "",
  aggregateRatingEnabled: false,
  ratingValue: 5,
  reviewCount: 0,
  websiteSchemaEnabled: true,
  searchboxEnabled: false,
  searchUrlTemplate: "/blog?q={search_term_string}",
  breadcrumbsEnabled: true,
  webPageSchemaEnabled: true,
  aeoEnabled: true,
  speakableEnabled: true,
  speakableSelectors: ["h1", ".post-takeaways", "article p"],
  faqSchemaEnabled: true,
  qaPageEnabled: false,
  llmsTxtEnabled: true,
  llmsTxtAutoGenerate: true,
  llmsTxtContent: "",
  aiSummary:
    "Carvi Associates is an Indian chartered accountancy firm providing statutory audit, income tax, GST, ROC compliance and business advisory services to founders, SMEs and growing enterprises.",
  entityDefinition:
    "Carvi Associates is a chartered accountancy (CA) firm registered in India that delivers audit, taxation, GST and regulatory compliance services.",
  aiAnswerTargets: [],
  rssEnabled: true,
  rssTitle: `${SITE_NAME} — Knowledge Desk`,
  rssDescription:
    "Practical notes on income tax, GST, company law and audit from the Carvi Associates team.",
  rssItemLimit: 20,
  manifestEnabled: true,
  manifestName: SITE_NAME,
  manifestShortName: "Carvi",
  manifestDescription: SITE_DESCRIPTION,
  manifestDisplay: "standalone",
  manifestStartUrl: "/",
  manifestBackgroundColor: "#faf5e9",
  manifestIcons: [],
  preconnectUrls: ["https://fonts.googleapis.com", "https://fonts.gstatic.com"],
  dnsPrefetchUrls: ["https://res.cloudinary.com"],
  hreflangEnabled: false,
  hreflangEntries: [],
  canonicalHost: "",
  forceTrailingSlash: false,
  redirectsEnabled: true,
  indexNowEnabled: false,
  indexNowKey: "",
  customHeadHtml: "",
  customBodyStartHtml: "",
  customBodyEndHtml: "",
};

export const defaultSeoRobotsRules: Array<Omit<SeoRobotsRuleItem, "id" | "deletedAt">> = [
  {
    userAgent: "*",
    allowPaths: ["/"],
    disallowPaths: ["/admin", "/admin/", "/api/", "/_next/", "/blog/tag/"],
    crawlDelay: null,
    notes: "Baseline rule for every crawler.",
    isActive: true,
    displayOrder: 0,
  },
  {
    userAgent: "Googlebot",
    allowPaths: ["/"],
    disallowPaths: ["/admin", "/api/"],
    crawlDelay: null,
    notes: "Google web crawler.",
    isActive: true,
    displayOrder: 1,
  },
  {
    userAgent: "Bingbot",
    allowPaths: ["/"],
    disallowPaths: ["/admin", "/api/"],
    crawlDelay: null,
    notes: "Bing and Copilot crawler.",
    isActive: true,
    displayOrder: 2,
  },
];

export const defaultSeoFaqs: Array<Omit<SeoFaqItem, "id" | "deletedAt">> = [
  {
    question: "What services does Carvi Associates provide?",
    answer:
      "Carvi Associates provides statutory and internal audit, income tax planning and filing, GST registration and returns, company incorporation, ROC and secretarial compliance, bookkeeping, and business advisory for Indian companies.",
    scope: "GLOBAL",
    pagePath: "",
    category: "Firm",
    keywords: "CA firm services, audit, tax, GST",
    isSpeakable: true,
    showOnPage: true,
    displayOrder: 0,
    isActive: true,
    isVisible: true,
  },
  {
    question: "Who should hire a chartered accountant in India?",
    answer:
      "Any business that is registered under the Companies Act, crosses the GST threshold, needs a statutory or tax audit, or wants reliable bookkeeping and tax planning should work with a chartered accountant. Startups typically engage a CA at incorporation to set up compliance correctly from day one.",
    scope: "GLOBAL",
    pagePath: "",
    category: "Advisory",
    keywords: "hire chartered accountant, CA India",
    isSpeakable: true,
    showOnPage: true,
    displayOrder: 1,
    isActive: true,
    isVisible: true,
  },
  {
    question: "How quickly does Carvi Associates respond to an enquiry?",
    answer:
      "Enquiries submitted through the website are answered within one business day, and urgent compliance deadlines are triaged the same day.",
    scope: "GLOBAL",
    pagePath: "",
    category: "Contact",
    keywords: "response time, contact CA",
    isSpeakable: true,
    showOnPage: true,
    displayOrder: 2,
    isActive: true,
    isVisible: true,
  },
];

export const defaultSeoPages = [
  {
    path: "/",
    label: "Homepage",
    title: `${SITE_NAME} | Chartered Accountants for Audit, Tax & GST`,
    description: SITE_DESCRIPTION,
    displayOrder: 0,
  },
  {
    path: "/blog",
    label: "Knowledge Desk",
    title: "Insights on Tax, GST & Business Compliance",
    description:
      "Plain-English notes on income tax, GST, company law and audit — written by the Carvi Associates team for founders and finance heads.",
    displayOrder: 1,
  },
  {
    path: "/insight",
    label: "Knowledge Bank",
    title: "Knowledge Bank — Calculators, Acts, Forms & Filing Portals",
    description:
      "Reference material for founders and finance teams: articles, calculators, statutory forms, acts, and the portals you file on.",
    displayOrder: 2,
  },
];
