import { z } from "zod";
import {
  SEO_CHANGE_FREQUENCIES,
  SEO_CONSENT_CATEGORIES,
  SEO_IMAGE_PREVIEWS,
  SEO_INTEGRATION_PROVIDERS,
  SEO_ORGANIZATION_TYPES,
  SEO_REDIRECT_MATCHES,
  SEO_REDIRECT_STATUS_CODES,
  SEO_SCOPE_KINDS,
  SEO_SCRIPT_PLACEMENTS,
  SEO_SCRIPT_SCOPES,
  SEO_SCRIPT_STRATEGIES,
  SEO_TWITTER_CARDS,
} from "@/lib/seo/types";

const text = z.string();
const optionalText = z.string().nullable().optional();
const stringList = z.array(z.string());

export const hreflangEntrySchema = z.object({
  hreflang: z.string().min(2),
  href: z.string().min(1),
});

export const openingHourSchema = z.object({
  days: z.array(z.string().min(2)).min(1),
  opens: z.string().min(1),
  closes: z.string().min(1),
});

export const contactPointSchema = z.object({
  contactType: z.string().min(1),
  telephone: z.string(),
  email: z.string(),
  areaServed: z.string(),
  availableLanguage: z.string(),
});

export const customVerificationSchema = z.object({
  name: z.string().min(1),
  content: z.string().min(1),
});

export const manifestIconSchema = z.object({
  src: z.string().min(1),
  sizes: z.string().min(1),
  type: z.string().min(1),
  purpose: z.string(),
});

export const scriptAttributeSchema = z.object({
  name: z.string().min(1),
  value: z.string(),
});

export const seoSettingsSchema = z.object({
  siteName: text.min(1),
  siteShortName: text,
  siteUrl: text.min(1),
  defaultTitle: text.min(1),
  titleTemplate: text,
  applyTitleTemplate: z.boolean(),
  defaultDescription: text.min(1),
  defaultKeywords: text,
  siteLanguage: text.min(2),
  siteLocale: text.min(2),
  alternateLocales: stringList,
  applicationName: text,
  publisherName: text,
  authorName: text,
  generatorName: text,
  copyrightText: text,
  categoryMeta: text,
  referrerPolicy: text,
  colorScheme: text,
  formatDetectionTelephone: z.boolean(),
  faviconUrl: text,
  faviconSmallUrl: text,
  appleTouchIconUrl: text,
  svgIconUrl: text,
  maskIconUrl: text,
  maskIconColor: text,
  themeColorLight: text,
  themeColorDark: text,
  indexingEnabled: z.boolean(),
  defaultNoIndex: z.boolean(),
  defaultNoFollow: z.boolean(),
  defaultNoArchive: z.boolean(),
  defaultNoSnippet: z.boolean(),
  defaultNoImageIndex: z.boolean(),
  maxSnippet: z.number().int().min(-1).max(10000),
  maxImagePreview: z.enum(SEO_IMAGE_PREVIEWS),
  maxVideoPreview: z.number().int().min(-1).max(10000),
  robotsEnabled: z.boolean(),
  robotsUseCustom: z.boolean(),
  robotsCustomContent: text,
  robotsExtraLines: text,
  robotsHost: text,
  robotsCrawlDelay: z.number().int().min(0).max(300).nullable(),
  blockAiCrawlers: z.boolean(),
  allowedAiCrawlers: stringList,
  sitemapEnabled: z.boolean(),
  sitemapIncludeImages: z.boolean(),
  sitemapIncludeBlog: z.boolean(),
  sitemapIncludeServices: z.boolean(),
  sitemapIncludeCategories: z.boolean(),
  sitemapIncludeTags: z.boolean(),
  sitemapIncludeAuthors: z.boolean(),
  sitemapIncludePages: z.boolean(),
  sitemapDefaultChangeFreq: z.enum(SEO_CHANGE_FREQUENCIES),
  sitemapHomePriority: z.number().min(0).max(1),
  sitemapPagePriority: z.number().min(0).max(1),
  sitemapBlogPriority: z.number().min(0).max(1),
  sitemapPostPriority: z.number().min(0).max(1),
  sitemapServicePriority: z.number().min(0).max(1),
  sitemapMaxUrls: z.number().int().min(100).max(50000),
  ogType: text,
  ogSiteName: text,
  ogImageUrl: text,
  ogImageAlt: text,
  ogImageWidth: z.number().int().min(200).max(4096),
  ogImageHeight: z.number().int().min(200).max(4096),
  twitterCard: z.enum(SEO_TWITTER_CARDS),
  twitterSite: text,
  twitterCreator: text,
  twitterImageUrl: text,
  facebookAppId: text,
  facebookPageUrl: text,
  googleSiteVerification: text,
  bingSiteVerification: text,
  yandexVerification: text,
  yahooVerification: text,
  pinterestVerification: text,
  facebookDomainVerification: text,
  baiduVerification: text,
  nortonVerification: text,
  customVerifications: z.array(customVerificationSchema),
  organizationEnabled: z.boolean(),
  organizationType: z.enum(SEO_ORGANIZATION_TYPES),
  organizationName: text,
  organizationLegalName: text,
  organizationAlternateName: text,
  organizationDescription: text,
  organizationLogoUrl: text,
  organizationImageUrl: text,
  foundingDate: text,
  founderName: text,
  contactEmail: text,
  contactPhone: text,
  faxNumber: text,
  priceRange: text,
  currenciesAccepted: text,
  paymentAccepted: text,
  streetAddress: text,
  addressLocality: text,
  addressRegion: text,
  postalCode: text,
  addressCountry: text,
  latitude: text,
  longitude: text,
  hasMapUrl: text,
  areaServed: stringList,
  openingHours: z.array(openingHourSchema),
  sameAs: stringList,
  contactPoints: z.array(contactPointSchema),
  knowsAbout: stringList,
  awards: stringList,
  slogan: text,
  numberOfEmployees: z.number().int().min(0).max(1000000).nullable(),
  taxId: text,
  vatId: text,
  registrationNumber: text,
  aggregateRatingEnabled: z.boolean(),
  ratingValue: z.number().min(0).max(5),
  reviewCount: z.number().int().min(0),
  websiteSchemaEnabled: z.boolean(),
  searchboxEnabled: z.boolean(),
  searchUrlTemplate: text,
  breadcrumbsEnabled: z.boolean(),
  webPageSchemaEnabled: z.boolean(),
  aeoEnabled: z.boolean(),
  speakableEnabled: z.boolean(),
  speakableSelectors: stringList,
  faqSchemaEnabled: z.boolean(),
  qaPageEnabled: z.boolean(),
  llmsTxtEnabled: z.boolean(),
  llmsTxtAutoGenerate: z.boolean(),
  llmsTxtContent: text,
  aiSummary: text,
  entityDefinition: text,
  aiAnswerTargets: stringList,
  rssEnabled: z.boolean(),
  rssTitle: text,
  rssDescription: text,
  rssItemLimit: z.number().int().min(1).max(200),
  manifestEnabled: z.boolean(),
  manifestName: text,
  manifestShortName: text,
  manifestDescription: text,
  manifestDisplay: text,
  manifestStartUrl: text,
  manifestBackgroundColor: text,
  manifestIcons: z.array(manifestIconSchema),
  preconnectUrls: stringList,
  dnsPrefetchUrls: stringList,
  hreflangEnabled: z.boolean(),
  hreflangEntries: z.array(hreflangEntrySchema),
  canonicalHost: text,
  forceTrailingSlash: z.boolean(),
  redirectsEnabled: z.boolean(),
  indexNowEnabled: z.boolean(),
  indexNowKey: text,
  customHeadHtml: text,
  customBodyStartHtml: text,
  customBodyEndHtml: text,
});

const pathField = z
  .string()
  .min(1)
  .refine((value) => value.startsWith("/"), "Path must start with a slash");

export const seoPageSchema = z.object({
  path: pathField,
  label: text,
  title: optionalText,
  description: optionalText,
  keywords: optionalText,
  canonicalUrl: optionalText,
  ogTitle: optionalText,
  ogDescription: optionalText,
  ogImageUrl: optionalText,
  ogImageAlt: optionalText,
  ogType: optionalText,
  twitterTitle: optionalText,
  twitterDescription: optionalText,
  twitterImageUrl: optionalText,
  twitterCard: z.enum(SEO_TWITTER_CARDS).nullable().optional(),
  noIndex: z.boolean(),
  noFollow: z.boolean(),
  noArchive: z.boolean(),
  noSnippet: z.boolean(),
  noImageIndex: z.boolean(),
  maxSnippet: z.number().int().min(-1).max(10000).nullable().optional(),
  maxImagePreview: z.enum(SEO_IMAGE_PREVIEWS).nullable().optional(),
  maxVideoPreview: z.number().int().min(-1).max(10000).nullable().optional(),
  breadcrumbLabel: optionalText,
  focusKeyword: text,
  secondaryKeywords: text,
  aiSummary: text,
  speakableSelectors: stringList,
  hreflangEntries: z.array(hreflangEntrySchema),
  customJsonLd: z.unknown().nullable().optional(),
  includeInSitemap: z.boolean(),
  sitemapPriority: z.number().min(0).max(1).nullable().optional(),
  sitemapChangeFreq: z.enum(SEO_CHANGE_FREQUENCIES).nullable().optional(),
  sitemapLastMod: z.string().nullable().optional(),
  notes: text,
  displayOrder: z.number().int().optional(),
  isActive: z.boolean(),
});

export const seoRedirectSchema = z.object({
  source: pathField,
  destination: z.string().min(1),
  statusCode: z.union([
    z.literal(SEO_REDIRECT_STATUS_CODES[0]),
    z.literal(SEO_REDIRECT_STATUS_CODES[1]),
    z.literal(SEO_REDIRECT_STATUS_CODES[2]),
    z.literal(SEO_REDIRECT_STATUS_CODES[3]),
  ]),
  matchType: z.enum(SEO_REDIRECT_MATCHES),
  preserveQuery: z.boolean(),
  notes: text,
  isActive: z.boolean(),
  displayOrder: z.number().int().optional(),
});

export const seoScriptSchema = z
  .object({
    name: z.string().min(1),
    description: text,
    placement: z.enum(SEO_SCRIPT_PLACEMENTS),
    strategy: z.enum(SEO_SCRIPT_STRATEGIES),
    scriptSrc: text,
    inlineCode: text,
    scriptType: text,
    isAsync: z.boolean(),
    isDefer: z.boolean(),
    attributes: z.array(scriptAttributeSchema),
    scope: z.enum(SEO_SCRIPT_SCOPES),
    pathPatterns: stringList,
    consentCategory: z.enum(SEO_CONSENT_CATEGORIES),
    isActive: z.boolean(),
    displayOrder: z.number().int().optional(),
  })
  .refine(
    (value) => value.scriptSrc.trim().length > 0 || value.inlineCode.trim().length > 0,
    "Provide a script URL or inline code",
  );

export const seoIntegrationSchema = z.object({
  provider: z.enum(SEO_INTEGRATION_PROVIDERS),
  label: text,
  trackingId: text,
  secondaryId: text,
  config: z.record(z.string(), z.unknown()),
  notes: text,
  isActive: z.boolean(),
  displayOrder: z.number().int().optional(),
});

export const seoRobotsRuleSchema = z.object({
  userAgent: z.string().min(1),
  allowPaths: stringList,
  disallowPaths: stringList,
  crawlDelay: z.number().int().min(0).max(300).nullable().optional(),
  notes: text,
  isActive: z.boolean(),
  displayOrder: z.number().int().optional(),
});

export const seoSitemapEntrySchema = z.object({
  url: z.string().min(1),
  changeFrequency: z.enum(SEO_CHANGE_FREQUENCIES),
  priority: z.number().min(0).max(1),
  lastModified: z.string().nullable().optional(),
  imageUrls: stringList,
  notes: text,
  isActive: z.boolean(),
  displayOrder: z.number().int().optional(),
});

export const seoFaqSchema = z.object({
  question: z.string().min(1),
  answer: z.string().min(1),
  scope: z.enum(SEO_SCOPE_KINDS),
  pagePath: text,
  category: text,
  keywords: text,
  isSpeakable: z.boolean(),
  showOnPage: z.boolean(),
  displayOrder: z.number().int().optional(),
  isActive: z.boolean(),
  isVisible: z.boolean(),
});

export const seoSchemaBlockSchema = z.object({
  name: z.string().min(1),
  schemaType: z.string().min(1),
  jsonLd: z.unknown(),
  scope: z.enum(SEO_SCOPE_KINDS),
  pagePath: text,
  notes: text,
  isActive: z.boolean(),
  displayOrder: z.number().int().optional(),
});

export const seoReorderSchema = z.object({
  orderedIds: z.array(z.string().min(1)).min(1),
});

export const seoBulkSchema = z.object({
  ids: z.array(z.string().min(1)).min(1),
  action: z.enum([
    "activate",
    "deactivate",
    "show",
    "hide",
    "soft-delete",
    "restore",
    "hard-delete",
    "duplicate",
  ]),
});

export const indexNowSchema = z.object({
  urls: z.array(z.string().min(1)).min(1).max(10000),
});
