import {
  ArrowUpRight,
  Banknote,
  Bell,
  Binary,
  Bookmark,
  Braces,
  Briefcase,
  Building2,
  Calculator,
  ChartColumn,
  Clock3,
  Cpu,
  Download,
  FileText,
  Globe2,
  Hash,
  HeartPulse,
  IdCard,
  Image as ImageIcon,
  KeyRound,
  Landmark,
  Lightbulb,
  Link2,
  Merge,
  Palette,
  Percent,
  QrCode,
  Receipt,
  Regex,
  Rocket,
  Scale,
  Scissors,
  Search,
  TextCursorInput,
  TrendingUp,
  UserRound,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  lightbulb: Lightbulb,
  zap: Zap,
  calculator: Calculator,
  bell: Bell,
  wrench: Wrench,
  link: Link2,
  scale: Scale,
  file: FileText,
  receipt: Receipt,
  landmark: Landmark,
  rocket: Rocket,
  building: Building2,
  percent: Percent,
  wallet: Wallet,
  banknote: Banknote,
  trending: TrendingUp,
  chart: ChartColumn,
  users: Users,
  merge: Merge,
  split: Scissors,
  image: ImageIcon,
  qr: QrCode,
  hash: Hash,
  braces: Braces,
  binary: Binary,
  key: KeyRound,
  text: TextCursorInput,
  clock: Clock3,
  palette: Palette,
  regex: Regex,
  cpu: Cpu,
  id: IdCard,
  user: UserRound,
  briefcase: Briefcase,
  globe: Globe2,
  heart: HeartPulse,
  download: Download,
  search: Search,
  arrow: ArrowUpRight,
  bookmark: Bookmark,
};

export function KnowledgeIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? FileText;
  return <Icon className={className} aria-hidden="true" />;
}
