import type {
  AboutContent,
  BookAppointmentContent,
  FeatureItem,
  HeroStat,
  HeroTrustItem,
  PartnerMarqueeItem,
  ServiceItem,
  ServicesSectionContent,
  TeamContent,
  TeamMemberItem,
  WhyChooseContent,
  WhyChooseItem,
  WorkingProcessContent,
  WorkingProcessStepItem,
} from "@/lib/cms/types";

export const defaultNavItems = [
  { label: "Home", href: "/", sortOrder: 0, visible: true },
  { label: "About Us", href: "#", sortOrder: 1, visible: true },
  { label: "Knowledge Bank", href: "#", sortOrder: 2, visible: true },
  { label: "Services", href: "#", sortOrder: 3, visible: true },
  { label: "Contact", href: "#", sortOrder: 4, visible: true },
];

export const defaultSocialLinks = [
  { label: "Facebook", href: "https://facebook.com", icon: "fa-facebook-f", sortOrder: 0, visible: true },
  { label: "X", href: "https://x.com", icon: "fa-twitter", sortOrder: 1, visible: true },
  { label: "Linkedin", href: "https://linkedin.com", icon: "fa-linkedin-in", sortOrder: 2, visible: true },
  { label: "Instagram", href: "https://instagram.com", icon: "fa-instagram", sortOrder: 3, visible: true },
];

export const defaultTopbar = {
  email: "hello@carviassociates.com",
  address: "25/09 Mozilla Golden Street",
  addressMapUrl: "https://www.google.com/maps",
  phone: "+91 5698 0036 420",
  phoneHref: "tel:+9156980036420",
  whatsappLabel: "WhatsApp Channel",
  whatsappHref: "https://whatsapp.com/channel/0029VaExampleChannelId",
};

export const defaultHeroStats: HeroStat[] = [
  {
    icon: "icon-trophy",
    end: 24,
    suffix: "+",
    label: "Years Experience",
  },
  {
    icon: "icon-business-and-finance",
    end: 500,
    suffix: "+",
    label: "Businesses Served",
  },
  {
    icon: "icon-analytics",
    end: 50,
    suffix: "+",
    label: "Industries",
  },
  {
    icon: "icon-folder",
    end: 1000,
    suffix: "+",
    label: "Returns Filed",
  },
];

export const defaultHeroTrust: HeroTrustItem[] = [
  { icon: "icon-satisfaction", label: "Chartered Accountants" },
  { icon: "icon-analysis", label: "Audit · Tax · Compliance" },
  { icon: "icon-location", label: "Pan-India Advisory" },
];

export const defaultHero = {
  tagline: "YOUR GROWTH. OUR COMMITMENT.",
  titleBeforeVideo: "Helping Businesses",
  titleHighlight: "Grow",
  titleAfterVideo: "with Confidence",
  description:
    "Expertise in Audit, Tax, Compliance & Advisory to help you stay compliant, reduce risks and scale your business.",
  secondaryCtaText: "Talk to an Expert",
  ctaText: "Book Free Consultation",
  ctaHref: "#",
  videoId: null as string | null,
  heroImageUrl: "https://bracketweb.com/findox-laravel/assets/images/hero-slider/hero-1-1.png",
  activeUserCount: 125,
  activeUserSuffix: "k+",
  activeUserLabel: "Active Users",
  activeUserImages: [
    "/images/resources/active-user-1.jpg",
    "/images/resources/active-user-2.jpg",
    "/images/resources/active-user-3.jpg",
  ],
  stats: defaultHeroStats,
  trust: defaultHeroTrust,
};

export const defaultHeader = {
  contactCtaText: "Contact Us",
  contactCtaHref: "#",
};

export const defaultPartnerMarqueeLabel = "Trusted by Businesses Across India";

export const defaultPartners: Omit<PartnerMarqueeItem, "id">[] = [
  {
    name: "Vasavi",
    tagline: "The Future Is Here",
    logoUrl: null,
    variant: "stacked",
    sortOrder: 0,
    visible: true,
  },
  {
    name: "Sree Constructions",
    tagline: null,
    logoUrl: null,
    variant: "script",
    sortOrder: 1,
    visible: true,
  },
  {
    name: "Pranava",
    tagline: "Constructions",
    logoUrl: null,
    variant: "dual",
    sortOrder: 2,
    visible: true,
  },
  {
    name: "Medi Life",
    tagline: "Hospitals",
    logoUrl: null,
    variant: "dual",
    sortOrder: 3,
    visible: true,
  },
  {
    name: "UrbanBite",
    tagline: null,
    logoUrl: null,
    variant: "brand",
    sortOrder: 4,
    visible: true,
  },
  {
    name: "Shree",
    tagline: "Marbles",
    logoUrl: null,
    variant: "dual",
    sortOrder: 5,
    visible: true,
  },
];

export const defaultFeatures: Omit<FeatureItem, "id">[] = [
  {
    icon: "icon-risk",
    title: "Financial Growth",
    text: "Financial Revenue solution in business and enhancing.",
    href: "#",
    sortOrder: 0,
    visible: true,
  },
  {
    icon: "icon-financial-presentation",
    title: "Finance Planning",
    text: "Supporting individuals in business challenges, and.",
    href: "#",
    sortOrder: 1,
    visible: true,
  },
  {
    icon: "icon-approach",
    title: "Business Advisory",
    text: "Thanks for taking the time to make the website, but i.",
    href: "#",
    sortOrder: 2,
    visible: true,
  },
];

export const defaultAbout: AboutContent = {
  tagline: "Our About Company",
  title: ["We Provide Professional Advice", "About This Finance."],
  text: "Business tailored design, management & support services Business business agency elit, sed do eiusmod tempor majority have in some we form, by injected humour solution.",
  experience: { value: "37+", label: "Years Experience" },
  images: {
    collageOne: "/images/about/about-1-1.jpg",
    collageTwo: "/images/about/about-1-2.jpg",
  },
  collageOneAlt: "Advisors reviewing a financial plan",
  collageTwoAlt: "Client consultation in progress",
  defaultTabId: "team-support",
  taglineBg: "#f4ebd8",
  tabs: [
    { id: "data-analysis", label: "Data Analysis", image: "/images/about/about-1-3.jpg" },
    { id: "team-support", label: "Team Support", image: "/images/about/about-1-4.jpg" },
    { id: "advertising", label: "Advertising", image: "/images/about/about-1-5.jpg" },
  ],
  checklist: [
    "Experienced & Skilled Team.",
    "Financial Audit Business Files.",
    "Lending & Credit Services.",
  ],
};

export const defaultServicesSection: ServicesSectionContent = {
  tagline: "Our Best Services",
  title: ["Expert Advice For Consulting", "Finance Services."],
  cardTagline: "Finance Strategic Business",
  taglineBg: "#fffdf8",
  isVisible: true,
  seoTitle: null,
  seoDescription: null,
  seoKeywords: null,
  canonicalUrl: null,
  ogImageUrl: null,
  twitterImageUrl: null,
  noIndex: false,
};

export const defaultServices: Omit<ServiceItem, "id" | "createdAt" | "updatedAt">[] = [
  {
    titleLine1: "Business Analytics",
    titleLine2: "Statistics",
    shortTitle: "Business Analytics",
    subtitle: null,
    description: "Delivering clear insight from complex financial data sets.",
    slug: "business-analytics-statistics",
    icon: "icon-stats-2",
    iconType: "icomoon",
    imageUrl: "/images/services/service-1-1.jpg",
    imageAlt: "Business analytics and statistics advisory",
    hoverImageUrl: null,
    badge: null,
    category: "Analytics",
    serviceType: "Consulting",
    accentColor: null,
    ctaText: "Learn more",
    ctaHref: "#",
    displayOrder: 0,
    isFeatured: true,
    isPopular: false,
    isActive: true,
    isVisible: true,
    publishedAt: null,
    deletedAt: null,
    seoTitle: null,
    seoDescription: null,
    seoKeywords: null,
    canonicalUrl: null,
    ogImageUrl: null,
    noIndex: false,
  },
  {
    titleLine1: "Personal Finance",
    titleLine2: "Services",
    shortTitle: "Personal Finance",
    subtitle: null,
    description: "Guiding individuals toward smarter long-term money decisions.",
    slug: "personal-finance-services",
    icon: "icon-agreement",
    iconType: "icomoon",
    imageUrl: "/images/services/service-1-2.jpg",
    imageAlt: "Personal finance services",
    hoverImageUrl: null,
    badge: null,
    category: "Finance",
    serviceType: "Advisory",
    accentColor: null,
    ctaText: "Learn more",
    ctaHref: "#",
    displayOrder: 1,
    isFeatured: false,
    isPopular: true,
    isActive: true,
    isVisible: true,
    publishedAt: null,
    deletedAt: null,
    seoTitle: null,
    seoDescription: null,
    seoKeywords: null,
    canonicalUrl: null,
    ogImageUrl: null,
    noIndex: false,
  },
  {
    titleLine1: "Banking & Business",
    titleLine2: "Accounts",
    shortTitle: "Banking & Accounts",
    subtitle: null,
    description: "Streamlined account structures built for growing businesses.",
    slug: "banking-business-accounts",
    icon: "icon-bank",
    iconType: "icomoon",
    imageUrl: "/images/services/service-1-3.jpg",
    imageAlt: "Banking and business accounts",
    hoverImageUrl: null,
    badge: null,
    category: "Banking",
    serviceType: "Accounts",
    accentColor: null,
    ctaText: "Learn more",
    ctaHref: "#",
    displayOrder: 2,
    isFeatured: false,
    isPopular: false,
    isActive: true,
    isVisible: true,
    publishedAt: null,
    deletedAt: null,
    seoTitle: null,
    seoDescription: null,
    seoKeywords: null,
    canonicalUrl: null,
    ogImageUrl: null,
    noIndex: false,
  },
  {
    titleLine1: "Financial Data Analysis",
    titleLine2: "Solutions",
    shortTitle: "Data Analysis",
    subtitle: null,
    description: "Turning raw numbers into confident, actionable strategy.",
    slug: "financial-data-analysis-solutions",
    icon: "icon-analysis",
    iconType: "icomoon",
    imageUrl: "/images/services/service-1-4.jpg",
    imageAlt: "Financial data analysis solutions",
    hoverImageUrl: null,
    badge: null,
    category: "Analytics",
    serviceType: "Solutions",
    accentColor: null,
    ctaText: "Learn more",
    ctaHref: "#",
    displayOrder: 3,
    isFeatured: false,
    isPopular: false,
    isActive: true,
    isVisible: true,
    publishedAt: null,
    deletedAt: null,
    seoTitle: null,
    seoDescription: null,
    seoKeywords: null,
    canonicalUrl: null,
    ogImageUrl: null,
    noIndex: false,
  },
  {
    titleLine1: "Strategic Finance",
    titleLine2: "Planning",
    shortTitle: "Finance Planning",
    subtitle: null,
    description: "Roadmaps that align today's budget with tomorrow's goals.",
    slug: "strategic-finance-planning",
    icon: "icon-planning",
    iconType: "icomoon",
    imageUrl: "/images/services/service-1-5.jpg",
    imageAlt: "Strategic finance planning",
    hoverImageUrl: null,
    badge: null,
    category: "Planning",
    serviceType: "Strategy",
    accentColor: null,
    ctaText: "Learn more",
    ctaHref: "#",
    displayOrder: 4,
    isFeatured: false,
    isPopular: false,
    isActive: true,
    isVisible: true,
    publishedAt: null,
    deletedAt: null,
    seoTitle: null,
    seoDescription: null,
    seoKeywords: null,
    canonicalUrl: null,
    ogImageUrl: null,
    noIndex: false,
  },
  {
    titleLine1: "24/7 Team Support",
    titleLine2: "Services",
    shortTitle: "Team Support",
    subtitle: null,
    description: "Always-on advisory support whenever a question comes up.",
    slug: "team-support-services",
    icon: "icon-support",
    iconType: "icomoon",
    imageUrl: "/images/services/service-1-6.jpg",
    imageAlt: "24/7 team support services",
    hoverImageUrl: null,
    badge: null,
    category: "Support",
    serviceType: "Support",
    accentColor: null,
    ctaText: "Learn more",
    ctaHref: "#",
    displayOrder: 5,
    isFeatured: false,
    isPopular: false,
    isActive: true,
    isVisible: true,
    publishedAt: null,
    deletedAt: null,
    seoTitle: null,
    seoDescription: null,
    seoKeywords: null,
    canonicalUrl: null,
    ogImageUrl: null,
    noIndex: false,
  },
];

export const defaultBookAppointment: BookAppointmentContent = {
  tagline: "Book Appointment Now",
  title: ["Get Any Kind Of Finance Service", "Free To Contact Us."],
  description:
    "Financial services provided company that help individuals get this now or other contacts manage money make investments capital.",
  primaryButtonText: "Get Started",
  primaryButtonHref: "#",
  secondaryButtonText: "Contact Now",
  secondaryButtonHref: "#",
  backgroundImageUrl: "/images/backgrounds/book-appointment-bg.jpg",
  backgroundImageAlt: "Book an appointment with Carvi Associates",
  taglineBg: "#f4ebd8",
  isVisible: true,
  seoTitle: null,
  seoDescription: null,
  seoKeywords: null,
  canonicalUrl: null,
  ogImageUrl: null,
  twitterImageUrl: null,
  noIndex: false,
};

export const defaultWhyChooseItems: Omit<WhyChooseItem, "id" | "createdAt" | "updatedAt">[] = [
  {
    icon: "icon-market-research",
    title: "Market Research Analysis",
    text: "Financial services provided company.",
    href: "#",
    displayOrder: 0,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
  {
    icon: "icon-data-visualization",
    title: "Data Analysis finance",
    text: "Business tailored design, management.",
    href: "#",
    displayOrder: 1,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
  {
    icon: "icon-advertisig-agency",
    title: "Digital of Marketing",
    text: "We need to make the new version clean.",
    href: "#",
    displayOrder: 2,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
];

export const defaultWhyChoose: WhyChooseContent = {
  tagline: "Why Choose Us",
  title: ["Consulting Solutions For Your", "Business Development."],
  description:
    "Business tailored design, management & support services Business business agency elit, sed do eiusmod tempor majority have in some we form, by injected humour solution.",
  taglineBg: "#f4ebd8",
  imageUrl: "/images/resources/why-choose-1-1.jpg",
  imageAlt: "Why choose Carvi Associates",
  shapeImageUrl: "/images/shapes/why-choose-shape-1-1.png",
  isVisible: true,
  seoTitle: null,
  seoDescription: null,
  seoKeywords: null,
  canonicalUrl: null,
  ogImageUrl: null,
  twitterImageUrl: null,
  noIndex: false,
  items: defaultWhyChooseItems.map((item, index) => ({
    id: `fallback-why-${index}`,
    ...item,
  })),
};

export const defaultTeamMembers: Omit<TeamMemberItem, "id" | "createdAt" | "updatedAt">[] = [
  { name: "Christine Rose", role: "Founder", imageUrl: "/images/team/team-1-1.png", imageAlt: "Christine Rose", href: "#", socials: [], displayOrder: 0, isVisible: true, isActive: true, deletedAt: null },
  { name: "Thomas Adison", role: "Co - Founder", imageUrl: "/images/team/team-1-2.png", imageAlt: "Thomas Adison", href: "#", socials: [], displayOrder: 1, isVisible: true, isActive: true, deletedAt: null },
  { name: "Jhone Doe", role: "Manager", imageUrl: "/images/team/team-1-3.png", imageAlt: "Jhone Doe", href: "#", socials: [], displayOrder: 2, isVisible: true, isActive: true, deletedAt: null },
  { name: "Sharon Ratley", role: "Marketer", imageUrl: "/images/team/team-1-4.png", imageAlt: "Sharon Ratley", href: "#", socials: [], displayOrder: 3, isVisible: true, isActive: true, deletedAt: null },
  { name: "Adlof Carr", role: "Business Consultant", imageUrl: "/images/team/team-1-5.png", imageAlt: "Adlof Carr", href: "#", socials: [], displayOrder: 4, isVisible: true, isActive: true, deletedAt: null },
  { name: "Isabella Leo", role: "Support Engineer", imageUrl: "/images/team/team-1-6.png", imageAlt: "Isabella Leo", href: "#", socials: [], displayOrder: 5, isVisible: true, isActive: true, deletedAt: null },
  { name: "Judith White", role: "Creative Director", imageUrl: "/images/team/team-1-7.png", imageAlt: "Judith White", href: "#", socials: [], displayOrder: 6, isVisible: true, isActive: true, deletedAt: null },
  { name: "Paul Dotson", role: "Partnership Lead", imageUrl: "/images/team/team-1-8.png", imageAlt: "Paul Dotson", href: "#", socials: [], displayOrder: 7, isVisible: true, isActive: true, deletedAt: null },
];

export const defaultTeam: TeamContent = {
  tagline: "OUR Team member",
  title: ["Our Financial Experts The Team", "Member Solution."],
  taglineBg: "#f4ebd8",
  isVisible: true,
  seoTitle: null,
  seoDescription: null,
  seoKeywords: null,
  canonicalUrl: null,
  ogImageUrl: null,
  twitterImageUrl: null,
  noIndex: false,
  members: defaultTeamMembers.map((member, index) => ({
    id: `fallback-team-${index}`,
    ...member,
  })),
};

export const defaultWorkingProcessSteps: Omit<
  WorkingProcessStepItem,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    stepLabel: "Step 01",
    title: "Market Analysis",
    text: "Financial work provided best investments capital.",
    imageUrl: "/images/resources/working-process-1-1.jpg",
    imageAlt: "Market Analysis",
    href: "#",
    displayOrder: 0,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
  {
    stepLabel: "Step 02",
    title: "Finance Planning",
    text: "We are teiduals in business challenges, of enhancing.",
    imageUrl: "/images/resources/working-process-1-2.jpg",
    imageAlt: "Finance Planning",
    href: "#",
    displayOrder: 1,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
  {
    stepLabel: "Step 03",
    title: "Investment Appraisal",
    text: "It is pleasure, but because those who do not know.",
    imageUrl: "/images/resources/working-process-1-3.jpg",
    imageAlt: "Investment Appraisal",
    href: "#",
    displayOrder: 2,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
  {
    stepLabel: "Step 04",
    title: "Completed Work",
    text: "Continually myocardinate holistic mindshare with.",
    imageUrl: "/images/resources/working-process-1-4.jpg",
    imageAlt: "Completed Work",
    href: "#",
    displayOrder: 3,
    isVisible: true,
    isActive: true,
    deletedAt: null,
  },
];

export const defaultWorkingProcess: WorkingProcessContent = {
  tagline: "Our Working Process",
  title: ["Over The Solution Work Financial", "Of Provided Company."],
  taglineBg: "#f4ebd8",
  isVisible: true,
  seoTitle: null,
  seoDescription: null,
  seoKeywords: null,
  canonicalUrl: null,
  ogImageUrl: null,
  twitterImageUrl: null,
  noIndex: false,
  steps: defaultWorkingProcessSteps.map((step, index) => ({
    id: `fallback-wp-${index}`,
    ...step,
  })),
};
